### PR TITLE
stop copy other people you mf

### PR DESCRIPTION
**Pull request by coolkidsrule101**
your are a fake dev stop copying other people plugins for your please you didnt make them so stop forking other people work and make your own

### CODE REVIEW

**Comment by Muqsit** [comment]
what?

**Comment by Thunder33345** [comment]
either ways i see nothing wrong with forking plugins 
again this is github, what you expect?

**Comment by HittmanA** [comment]
Also, he forgot to mention his one repository on his profile is a fork of KitUI XD

**Comment by coolkidsrule101** [comment]
.....that was a 3month ago and I never did anything to it that when I was
new to gut hub dum ass

**Comment by Thunder33345** [comment]
why even edit this shit?

**Pull request closed without merging**
